# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf7539f5a1e2ef66903ebbeab39ea9a670fa74b89b498cda66c6a84084f4b062acaf429f6000330387e81497bdb9304ec8bd35bc69b4f1b92f7c395aba69d29

test:
  secret_key_base: bbf5cc87c51914603721cd7f4bb247db84c8736e2da5154c4decffa6b78a5e63f47e5c358a6cfed9fc7137dac2bc6cabcb92007fe4c84b44274a9bc159e1492c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
